{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e00c7670-fb4a-4976-bb54-4dda13adb2a3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# main.py\n",
    "\n",
    "from dotenv import load_dotenv\n",
    "import os\n",
    "\n",
    "from fastapi import FastAPI\n",
    "from fastapi.staticfiles import StaticFiles\n",
    "from fastapi.responses import FileResponse\n",
    "from fastapi.middleware.cors import CORSMiddleware\n",
    "\n",
    "# .env 파일 로드\n",
    "load_dotenv()  \n",
    "\n",
    "# (선택) CORS 설정 — 프론트엔드와 분리 개발 시 필요\n",
    "origins = [\n",
    "    os.getenv(\"FRONTEND_URL\", \"*\"),\n",
    "]\n",
    "\n",
    "app = FastAPI()\n",
    "\n",
    "app.add_middleware(\n",
    "    CORSMiddleware,\n",
    "    allow_origins=origins,\n",
    "    allow_credentials=True,\n",
    "    allow_methods=[\"*\"],\n",
    "    allow_headers=[\"*\"],\n",
    ")\n",
    "\n",
    "# 라우터 import\n",
    "from routers.health import router as health_router\n",
    "from routers.recommend import router as recommend_router\n",
    "from routers.paper import router as paper_router\n",
    "from routers.auth import router as auth_router\n",
    "from routers.mypage import router as mypage_router\n",
    "from routers.bookmark import router as bookmark_router\n",
    "\n",
    "# 라우터 등록\n",
    "app.include_router(health_router,    prefix=\"/health\",   tags=[\"health\"])\n",
    "app.include_router(recommend_router, tags=[\"recommend\"])\n",
    "app.include_router(paper_router,     prefix=\"/papers\",    tags=[\"papers\"])\n",
    "app.include_router(auth_router,      prefix=\"/auth\",      tags=[\"auth\"])\n",
    "app.include_router(mypage_router)\n",
    "app.include_router(bookmark_router)\n",
    "\n",
    "# 정적 파일 제공\n",
    "app.mount(\"/static\", StaticFiles(directory=\"static\"), name=\"static\")\n",
    "\n",
    "# SPA 진입점\n",
    "@app.get(\"/\", include_in_schema=False)\n",
    "async def serve_index():\n",
    "    return FileResponse(\"static/index.html\")\n",
    "\n",
    "\n",
    "# Uvicorn 실행 지원\n",
    "if __name__ == \"__main__\":\n",
    "    import uvicorn\n",
    "    uvicorn.run(\n",
    "        \"main:app\",\n",
    "        host=\"0.0.0.0\",\n",
    "        port=int(os.getenv(\"PORT\", 8000)),\n",
    "        reload=True\n",
    "    )"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
