{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "38521957-561b-4d70-bc9d-86be56230f1e",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"create papers table\n",
    "\n",
    "Revision ID: 8deb3e0e7465\n",
    "Revises: \n",
    "Create Date: 2025-05-22 22:57:46.242000\n",
    "\n",
    "\"\"\"\n",
    "from typing import Sequence, Union\n",
    "\n",
    "from alembic import op\n",
    "import sqlalchemy as sa\n",
    "\n",
    "\n",
    "# revision identifiers, used by Alembic.\n",
    "revision: str = '8deb3e0e7465'\n",
    "down_revision: Union[str, None] = None\n",
    "branch_labels: Union[str, Sequence[str], None] = None\n",
    "depends_on: Union[str, Sequence[str], None] = None\n",
    "\n",
    "\n",
    "def upgrade() -> None:\n",
    "    \"\"\"Upgrade schema.\"\"\"\n",
    "    # ### commands auto generated by Alembic - please adjust! ###\n",
    "    op.create_table('papers',\n",
    "    sa.Column('id', sa.Integer(), nullable=False),\n",
    "    sa.Column('title', sa.String(), nullable=True),\n",
    "    sa.Column('authors', sa.String(), nullable=True),\n",
    "    sa.Column('journal', sa.String(), nullable=True),\n",
    "    sa.Column('pub_date', sa.Date(), nullable=True),\n",
    "    sa.Column('link_url', sa.String(), nullable=True),\n",
    "    sa.PrimaryKeyConstraint('id')\n",
    "    )\n",
    "    op.create_index(op.f('ix_papers_id'), 'papers', ['id'], unique=False)\n",
    "    op.create_index(op.f('ix_papers_journal'), 'papers', ['journal'], unique=False)\n",
    "    op.create_index(op.f('ix_papers_title'), 'papers', ['title'], unique=False)\n",
    "    # ### end Alembic commands ###\n",
    "\n",
    "\n",
    "def downgrade() -> None:\n",
    "    \"\"\"Downgrade schema.\"\"\"\n",
    "    # ### commands auto generated by Alembic - please adjust! ###\n",
    "    op.drop_index(op.f('ix_papers_title'), table_name='papers')\n",
    "    op.drop_index(op.f('ix_papers_journal'), table_name='papers')\n",
    "    op.drop_index(op.f('ix_papers_id'), table_name='papers')\n",
    "    op.drop_table('papers')\n",
    "    # ### end Alembic commands ###"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
