{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f4c1f787-110c-4fa5-9aea-92e67305b375",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"add users table\n",
    "\n",
    "Revision ID: ed10f7041d46\n",
    "Revises: 8deb3e0e7465\n",
    "Create Date: 2025-05-22 23:26:27.786798\n",
    "\n",
    "\"\"\"\n",
    "from typing import Sequence, Union\n",
    "\n",
    "from alembic import op\n",
    "import sqlalchemy as sa\n",
    "\n",
    "\n",
    "# revision identifiers, used by Alembic.\n",
    "revision: str = 'ed10f7041d46'\n",
    "down_revision: Union[str, None] = '8deb3e0e7465'\n",
    "branch_labels: Union[str, Sequence[str], None] = None\n",
    "depends_on: Union[str, Sequence[str], None] = None\n",
    "\n",
    "\n",
    "def upgrade() -> None:\n",
    "    \"\"\"Upgrade schema.\"\"\"\n",
    "    # ### commands auto generated by Alembic - please adjust! ###\n",
    "    pass\n",
    "    # ### end Alembic commands ###\n",
    "\n",
    "\n",
    "def downgrade() -> None:\n",
    "    \"\"\"Downgrade schema.\"\"\"\n",
    "    # ### commands auto generated by Alembic - please adjust! ###\n",
    "    pass\n",
    "    # ### end Alembic commands ###"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
